import Head from 'next/head'
import Hero from '../components/hero.js'
import Navbar from '../components/navbar'
import styles from '../scss/Home.module.scss'
import Features from '../components/features'
import Features2 from '../components/features2'
import Partener from '../components/partener'
import Bussiness from '../components/bussiness.js'
import Stories from '../components/stories.js'
import Features4 from '../components/features4.js'
import Features5 from '../components/feactures5'
import Counter from '../components/counter.js'
import Scor from '../components/scor.js'
import Footer from '../components/footer.js'
import Images from '../components/images.js' 



export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       <div className={styles.home3}>
        <Navbar/>
        <Hero/>
       </div> 
       <Images/>
       <Features/>
        <div className={styles.features2}>
          <Features2/>
        </div>
          <Partener/>
          <Bussiness/>
          <Stories/>
          <Features4/>
          <Features5/>
          <Counter/>
          <Scor/>
          <Footer/>
      </main>
    </div>
  )
}
